// Code generated by internal/genmodels from the public catalog; DO NOT EDIT.

package avelin

// Models in the public catalog (https://api.avelin.ai/public/models.json).
const (
	// ModelAgenticFast is Avelin Agentic Fast: 256000-token context, input: text.
	ModelAgenticFast ModelID = "avelin-agentic-fast"
	// ModelAgenticPro is Avelin Agentic Pro: 256000-token context, input: text.
	ModelAgenticPro ModelID = "avelin-agentic-pro"
	// ModelAgenticUltra is Avelin Agentic Ultra: 256000-token context, input: text.
	ModelAgenticUltra ModelID = "avelin-agentic-ultra"
	// ModelCodingFast is Avelin Coding Fast: 1000000-token context, input: text.
	ModelCodingFast ModelID = "avelin-coding-fast"
	// ModelCodingPro is Avelin Coding Pro: 1000000-token context, input: text.
	ModelCodingPro ModelID = "avelin-coding-pro"
	// ModelCodingUltra is Avelin Coding Ultra: 1000000-token context, input: text.
	ModelCodingUltra ModelID = "avelin-coding-ultra"
	// ModelFast is Avelin Fast: 256000-token context, input: text, image.
	ModelFast ModelID = "avelin-fast"
	// ModelPro is Avelin Pro: 256000-token context, input: text, image.
	ModelPro ModelID = "avelin-pro"
	// ModelUltra is Avelin Ultra: 256000-token context, input: text, image.
	ModelUltra ModelID = "avelin-ultra"
)
