// Command genmodels generates models_gen.go: one avelin.ModelID constant per
// model in the public catalog at https://api.avelin.ai/public/models.json.
//
//	go run ./internal/genmodels [-in file] [-out models_gen.go] [-snapshot file]
//
// With -in it reads a saved catalog instead of fetching it. With -snapshot it
// also saves the catalog it read, which keeps the test fixture in sync.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
	"unicode"
)

const catalogURL = "https://api.avelin.ai/public/models.json"

func main() {
	in := flag.String("in", "", "read the catalog from this file instead of "+catalogURL)
	out := flag.String("out", "models_gen.go", "output Go file")
	snapshot := flag.String("snapshot", "", "also write the catalog JSON to this file")
	flag.Parse()

	data, err := readCatalog(*in)
	if err != nil {
		log.Fatal(err)
	}
	src, err := generate(data)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
	if *snapshot != "" {
		if err := os.WriteFile(*snapshot, data, 0o644); err != nil {
			log.Fatal(err)
		}
	}
}

func readCatalog(path string) ([]byte, error) {
	if path != "" {
		return os.ReadFile(path)
	}
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(catalogURL)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GET %s: %s", catalogURL, resp.Status)
	}
	return io.ReadAll(resp.Body)
}

// generate returns the formatted source of models_gen.go for a catalog.
func generate(catalog []byte) ([]byte, error) {
	var parsed struct {
		Data []struct {
			ID              string   `json:"id"`
			Name            string   `json:"name"`
			InputModalities []string `json:"input_modalities"`
			ContextLength   int      `json:"context_length"`
		} `json:"data"`
	}
	if err := json.Unmarshal(catalog, &parsed); err != nil {
		return nil, fmt.Errorf("parse catalog: %w", err)
	}
	if len(parsed.Data) == 0 {
		return nil, fmt.Errorf("catalog has no models")
	}
	models := parsed.Data
	sort.Slice(models, func(i, j int) bool { return models[i].ID < models[j].ID })

	var b bytes.Buffer
	b.WriteString("// Code generated by internal/genmodels from the public catalog; DO NOT EDIT.\n\n")
	b.WriteString("package avelin\n\n")
	b.WriteString("// Models in the public catalog (" + catalogURL + ").\nconst (\n")
	seen := map[string]string{}
	for _, m := range models {
		name := constName(m.ID)
		if prev, ok := seen[name]; ok {
			return nil, fmt.Errorf("models %q and %q both map to %s", prev, m.ID, name)
		}
		seen[name] = m.ID
		fmt.Fprintf(&b, "\t// %s is %s: %d-token context, input: %s.\n", name, m.Name, m.ContextLength, strings.Join(m.InputModalities, ", "))
		fmt.Fprintf(&b, "\t%s ModelID = %q\n", name, m.ID)
	}
	b.WriteString(")\n")
	return format.Source(b.Bytes())
}

// constName maps "avelin-coding-pro" to "ModelCodingPro".
func constName(id string) string {
	parts := strings.FieldsFunc(strings.TrimPrefix(id, "avelin-"), func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	var b strings.Builder
	b.WriteString("Model")
	for _, p := range parts {
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}
